### ISSUE TITLE
Latest module version is wrong on The Forge

### ISSUE THREAD

**Issue by ravingdragoon** [League-of-Foundry-Developers/fvtt-module-lmrtfy#145]
The game versioning added an extra period between versions 1.25 and 1.2.6 resulting in The forge seeing 1.25 as the latest version instead of the current 1.2.9 because 1.25 is a higher number than 1.2.x.  I'm not sure if this is an issue for you to fix, or for @kakaroto to work on on The Forge.

**Comment by kakaroto** [comment]
Thanks for the ping @ravingdragoon, I looked at fixing it, but if the issue was that `1.2.5` was marked as `1.25` by mistake, it would have been easy to change the version name so the versions are ordered properly, but this doesn't look to be the case here.
As you can see from the listing of versions here : https://forge-vtt.com/bazaar/package/lmrtfy
![image](https://user-images.githubusercontent.com/27990/154320997-04bea7e4-c315-43e8-b242-a2c3abf0c533.png)
![image](https://user-images.githubusercontent.com/27990/154321044-e1c34f92-5712-4f4b-98ef-3b90633b668e.png)
There are many versions that used a different versioning scheme, and version `1.2` is old, and going from `1.25` to `1.2.6` is downgrading the version.
While this is more apparent on the Forge, I would presume that even self hosted users who would be on `1.25` would not get the update to `1.2.6` (or `1.2.9` as the latest), as it would be considered a downgrade.
The solution here would be to either release a new version as `1.30.0` or switch entirely to `2.0.0` at this point with the new semantic versioning.

**Comment by Varriount** [comment]
I think switching to 2.0.0 would probably be the best move here.

**Comment by Varriount** [comment]
@kakaroto @ravingdragoon Can you confirm that the correct module version is listed in The Forge? I can see that the new version is listed on Foundry's module page.

**Comment by kakaroto** [comment]
> @kakaroto @ravingdragoon Can you confirm that the correct module version is listed in The Forge? I can see that the new version is listed on Foundry's module page.

I see it as ".2.0.0" which matches the version you had in the module.json : 
![image](https://user-images.githubusercontent.com/27990/154835062-d2e7119d-fda8-474a-9608-898335ae47e8.png)

I'll change it in the DB tomorrow so it appears as `2.0.0` but you should make sure your next tags are of the format `v2.1.0` and not `v.2.1.0`
You can check it the package here btw : 
https://forge-vtt.com/bazaar/package/lmrtfy
