### ISSUE TITLE
When rolling tables using LMRTFY, the chat output is incomplete

### ISSUE THREAD

**Issue by SavageNH** [League-of-Foundry-Developers/fvtt-module-lmrtfy#56]
I'm having a bit of trouble with module and was wondering if there is a fix I can implement on my end. Specifically, I'm using the "Better Roll Tables module to produce a rolltable that creates a random output of currency and loot from a defined list for an item I created in my campaign called the "Chest of Many Fortunes". Now, when I roll that table directly from the Better Roll Tables module, the output looks correct like this:

![better-rolltables-result](https://user-images.githubusercontent.com/35549167/107214994-b8403480-69d8-11eb-8900-5a2bf8186d00.jpg)

However, when I request a roll from my players using the "Let me roll that for you" module, the results look (incorrectly) like this:

![let-me-roll-it-result](https://user-images.githubusercontent.com/35549167/107215065-cdb55e80-69d8-11eb-9835-1b286d688d4c.jpg)

I should note I've tried this with the better roll tables module disabled as well, and got the same result from the standard issue roll tables, so I believe the issue lies somewhere within the LMRTFY module.

**Comment by akrigline** [comment]
Thanks for the detailed report!

@vtt-lair can you take a look at this? If not I'll add it to my to do list.

**Comment by jessev14** [comment]
DSN also don't seem to animate when rolling on them through LMRTFY. Can confirm that the dice animate when the table is rolled traditionally.

**Comment by vtt-lair** [comment]
@akrigline I'll add it to my to do list and hopefully see what I can do in the next or following week.

The problem here is how Foundry handles the roll table calls. The call that automatically outputs the result to the display (which gives you the roll table look and feel), doesn't allow you to make the call for a specific actor. As such, if you request 2 or more people to roll on a table you won't know who made each roll. I had it like this on the first iteration.

I changed it to be in line with the rest of the module, so that the roll is "made" by the requested actor. I did this by rolling on the table without displaying to chat, then using the result to build up a chat message sent by the specific actor.

I'll see what I can do with this.

**Comment by akrigline** [comment]
Big thanks for contributing, no pressure if you can't take a crack at this, let us know and we'll see what we can do.

**Comment by SavageNH** [comment]
Thank you for taking the time to look into this. I know it might sound a bit silly, but that item is actually integral to moving the story forward, as one of the 7 players in my group will receive a one-of-a-kind item at random that will allow the rest to follow through a portal, and I haven't figured out a better way to implement it.

**Comment by SavageNH** [comment]
Please let me know if there is anything else I can do to help you folks diagnose this bug.

**Comment by vtt-lair** [comment]
This was fixed with version v1.1.4 that has been released.
